---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- My First Group:
    - My First Service:
        href: http://docker.gonzalez.lv:3000/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://docker.gonzalez.lv:3000/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://docker.gonzalez.lv:3000/
        description: Homepage is 😎
